name: Deb package

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: kvmd-debian

      - name: Install dependencies
        working-directory: kvmd-debian
        run: |
          sudo apt-get update
          sudo apt-get install debhelper
          sudo apt-get install $(dpkg-checkbuilddeps |& cut -d':' -f4 | sed 's/([^)]*)//g')

      - name: Build
        working-directory: kvmd-debian
        run: |
          dpkg-buildpackage -rfakeroot --no-sign --build=binary

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debs
          path: ./*.deb

      - name: Release
        if: startsWith(github.ref, 'refs/tags/debian-')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files:
            ./*.deb
